# Generated by Django 5.0.2 on 2024-04-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
